# Generated by Django 5.1.1 on 2024-09-14 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('company_name', models.CharField(max_length=256)),
                ('job_title', models.CharField(max_length=256)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('user', 'company_name', 'application_date')},
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('text', models.CharField(max_length=256)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('resume', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('text', models.CharField(max_length=256)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('resume', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('url', models.URLField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('resume', 'user')},
            },
        ),
    ]
