# Generated by Django 5.1.1 on 2024-09-14 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='text',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='address',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='zip_code',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('institution', models.CharField(max_length=256)),
                ('degree', models.CharField(max_length=256)),
                ('start_date', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=256)),
                ('gpa', models.IntegerField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('language', models.CharField(max_length=256)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('name', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=256)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('reference', models.CharField(max_length=256)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('user', 'resume')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
                ('skill', models.CharField(max_length=256)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.resume')),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
